version: '3.7'

services:
  csharp:
    container_name: "csharp-web"
    build: .
    volumes:
      - ./app:/app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports: 
     - "8082:5000"
    tty: true
