version: '3.7'

services:
  csharp:
    container_name: "csharp-web"
    image: mcr.microsoft.com/dotnet/sdk:7.0
    volumes:
      - ./app:/app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports: 
     - "8081:5000"
    working_dir: /app
    tty: true
