version: '3.7'

services:
  csharp:
    build: .
    container_name: csharp-web
    volumes:
      - ./app:/app
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
    ports: 
     - "8081:5000"
    working_dir: /app
    tty: true
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    cap_add:
      - SYS_PTRACE
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Yahoo123!!"
      MSSQL_ENCRYPT: "false"
      TZ: "America/New_York"

